name: dns

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    networks:
      - proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8980:80/tcp
      - 3000:3000/tcp # Initial installation
    environment:
      TZ: Asia/Tokyo
    volumes:
      - $BACKUP_DIR/adguardhome/opt/adguardhome/work:/opt/adguardhome/work
      - $BACKUP_DIR/adguardhome/opt/adguardhome/conf:/opt/adguardhome/conf
    restart: always

networks:
  proxy:
    external: true