name: homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    environment:
      TZ: Asia/Tokyo
      PUID: 1000
      PGID: 1000
    ports:
      - 3001:3000
    volumes:
      - /docker/homepage/app/config:/app/config
    restart: unless-stopped

networks:
  proxy:
    external: true