name: monitoring

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - proxy
    environment:
      TZ: Asia/Tokyo
    # ports:
    #   - 3002:3000
    volumes:
      - /docker/grafana/var/lib/grafana:/var/lib/grafana
    restart: unless-stopped
    user: "$UID:$GID"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - proxy
    environment:
      TZ: Asia/Tokyo
    # ports:
    #   - 9090:9090
    volumes:
      - /docker/prometheus/etc/prometheus:/etc/prometheus
      - /docker/prometheus/prometheus:/prometheus
    restart: unless-stopped
    user: "$UID:$GID"
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    networks:
      - proxy
    environment:
      TZ: Asia/Tokyo
    # ports:
    #   - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped

networks:
  proxy:
    external: true