name: nextcloud

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    networks:
      - proxy
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - nextcloud_aio_nextcloud_datadir:/fake
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 18080:8080
    environment:
      TZ: Asia/Tokyo
      APACHE_PORT: 11000
      APACHE_IP_BINDING: 0.0.0.0
      APACHE_ADDITIONAL_NETWORK: proxy
      SKIP_DOMAIN_VALIDATION: false
      NEXTCLOUD_DATADIR: nextcloud_aio_nextcloud_datadir
    restart: unless-stopped

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver: local
    driver_opts:
      type: none
      device: /docker/nextcloud/mnt/docker-aio-config
      o: bind

  nextcloud_aio_nextcloud_datadir:
    name: nextcloud_aio_nextcloud_datadir
    driver: local
    driver_opts:
      type: cifs
      device: $LINUX_SHARE/nextcloud
      o: username=$USERNAME,password=$PASSWORD,uid=33,gid=0,file_mode=0770,dir_mode=0770

networks:
  proxy:
    external: true