name: nextcloud

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9080:80
      - 18080:8080
      - 8443:8443
    environment:
      TZ: Asia/Tokyo
    restart: unless-stopped

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
    driver: local
    driver_opts:
      type: cifs
      device: $BACKUP_SHARE/nextcloud/mnt/docker-aio-config
      o: username=$USERNAME,password=$PASSWORD,uid=33,gid=0,file_mode=0770,dir_mode=0770