name: proxy

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - proxy
    volumes:
      - /docker/traefik/etc/traefik:/etc/traefik
      - /docker/traefik/letsencrypt:/letsencrypt
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 444:444
    environment:
      TZ: Asia/Tokyo
      CF_DNS_API_TOKEN_FILE: $CF_DNS_API_TOKEN_FILE
    restart: always

networks:
  proxy:
    external: true