name: proxy

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - proxy
    volumes:
      - $BACKUP_DIR/traefik/etc/traefik:/etc/traefik
      - traefik_letsencrypt:/letsencrypt
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 444:444
    environment:
      TZ: Asia/Tokyo
      CF_DNS_API_TOKEN_FILE: $CF_DNS_API_TOKEN_FILE
    restart: always

volumes:
  traefik_letsencrypt:
    name: traefik_letsencrypt
    driver: local
    driver_opts:
      type: cifs
      device: $LINUX_SHARE/docker/traefik/letsencrypt
      o: username=$USERNAME,password=$PASSWORD,file_mode=0600,dir_mode=0600

networks:
  proxy:
    external: true