name: log-monitoring

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - proxy
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3100:3100
    volumes:
      - /docker/loki/etc/loki:/etc/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      - proxy
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /docker/promtail/etc/promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log
    restart: unless-stopped

networks:
  proxy:
    external: true