services:
  adguardhome:
    image: adguard/adguardhome:latest
    networks:
      - reverse-proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 8980:80/tcp
      # - 3000:3000/tcp # Initial installation
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /docker/adguardhome/opt/adguardhome/work:/opt/adguardhome/work
      - /docker/adguardhome/opt/adguardhome/conf:/opt/adguardhome/conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == docker-01]
      restart_policy:
        condition: any

networks:
  reverse-proxy:
    external: true