services:
  traefik:
    image: traefik:latest
    networks:
      - reverse-proxy
    volumes:
      - /docker/traefik/etc/traefik:/etc/traefik
      - /docker/traefik/letsencrypt:/letsencrypt
      - /var/log/traefik:/var/log/traefik
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 444:444
    environment:
      TZ: Asia/Tokyo
      CF_DNS_API_TOKEN_FILE: $CF_DNS_API_TOKEN_FILE
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == docker-01]
      restart_policy:
        condition: any

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    networks:
      - reverse-proxy
    volumes:
      - /docker/crowdsec/var/lib/crowdsec/data:/var/lib/crowdsec/data
      - /docker/crowdsec/etc/crowdsec:/etc/crowdsec
      - /var/log/traefik:/var/log/traefik:ro
    environment:
      TZ: Asia/Tokyo
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == docker-01]
      restart_policy:
        condition: any

networks:
  reverse-proxy:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24