name: frigate

services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: 128mb
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/frigate/config:/config
      - $MEDIA_DIR/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
      # - 5000:5000 # Internal unauthenticated access. Expose carefully.
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp
    environment:
      FRIGATE_IP: $FRIGATE_IP
      FRIGATE_RESTREAM_RTSP_USERNAME: $FRIGATE_RESTREAM_RTSP_USERNAME
      FRIGATE_RESTREAM_RTSP_PASSWORD: $FRIGATE_RESTREAM_RTSP_PASSWORD
      FRIGATE_RTSP_USERNAME: $FRIGATE_RTSP_USERNAME
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD
      FRIGATE_LIVING_CAMERA_IP: $FRIGATE_LIVING_CAMERA_IP
      FRIGATE_TAPO_PASSWORD: $FRIGATE_TAPO_PASSWORD
    deploy: # NVIDIA GPU (need install NVIDIA Container Toolkit before deploy)
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]